<!ELEMENT Configuration (Properties,Appenders,Loggers)>
<!ATTLIST Configuration status NMTOKEN #REQUIRED>
<!ELEMENT Properties (Property+)>
<!ELEMENT Property (#PCDATA)>
<!ATTLIST Property name NMTOKEN #REQUIRED>
<!ELEMENT Appenders (Console,RollingFile)>
<!ELEMENT Console (PatternLayout)>
<!ATTLIST Console name NMTOKEN #REQUIRED>
<!ATTLIST Console target NMTOKEN #REQUIRED>
<!ATTLIST Console follow NMTOKEN #REQUIRED>
<!ELEMENT PatternLayout EMPTY>
<!ATTLIST PatternLayout pattern CDATA #REQUIRED>
<!ELEMENT RollingFile (PatternLayout,Policies,DefaultRolloverStrategy)>
<!ATTLIST RollingFile name NMTOKEN #REQUIRED>
<!ATTLIST RollingFile fileName CDATA #REQUIRED>
<!ATTLIST RollingFile filePattern CDATA #REQUIRED>
<!ELEMENT Policies (TimeBasedTriggeringPolicy)>
<!ELEMENT TimeBasedTriggeringPolicy EMPTY>
<!ATTLIST TimeBasedTriggeringPolicy filePattern CDATA #REQUIRED>
<!ELEMENT DefaultRolloverStrategy EMPTY>
<!ATTLIST DefaultRolloverStrategy max NMTOKEN #REQUIRED>
<!ELEMENT Loggers (Logger,Root)>
<!ELEMENT Logger (AppenderRef+)>
<!ATTLIST Logger name NMTOKEN #REQUIRED>
<!ATTLIST Logger additivity NMTOKEN #REQUIRED>
<!ELEMENT AppenderRef EMPTY>
<!ATTLIST AppenderRef ref NMTOKEN #REQUIRED>
<!ELEMENT Root (AppenderRef+)>
<!ATTLIST Root level NMTOKEN #REQUIRED>